var lang = 0
// Create an object that maps IDs to arrays
const idMap = {
  "menu_home": [menu_home],
  "menu_about": [menu_about],
  "menu_product": [menu_product],
  "menu_service": [menu_service],
  "menu_contact": [menu_contact],
  "menu_online": [menu_online],
  "menu_product_1": product_lily_h,
  "menu_product_2": product_kuru_h,
  "menu_product_3": product_tharn_h,
  "menu_product_4": product_herb_h,
  "section-about-h1": about_h1,
  "section-about-p1": [about_p1],
  "section-about-h2": [about_h2],
  "section-about-p2": [about_p2],
  "section-about-h3": [about_h3.toUpperCase()],
  "section-about-p3": [about_p3],
  "section-why-us-h": [why_us_h],
  "section-why-us-l": [why_us_l],
  "section-why-us-p": [why_us_p],
  "section-product-h": product_h,
  "product_lily_h": product_lily_h,
  "product_kuru_h": product_kuru_h,
  "product_tharn_h": product_tharn_h,
  "product_herb_h": product_herb_h,
  "section-service-h": service_h,
  "section-service-p": [service_p],
  "section-service-s1-h": [service_s1_h.toUpperCase()],
  "section-service-s1-p": [service_s1_p],
  "section-service-s2-h": [service_s2_h.toUpperCase()],
  "section-service-s2-p": [service_s2_p],
  "section-service-s3-h": [service_s3_h.toUpperCase()],
  "section-service-s3-p": [service_s3_p],
  "section-oem-h": oem_h,
  "section-oem-p": oem_p,
  "section-oem-l": oem_l,
  "menu-about": about_h,
  "menu-product": product_h,
  "menu-service": service_h,
  "section-contact-h": contact_h,
  "section-contact-address": [address],
  "section-contact-email": [email],
  "section-contact-telnum": [telnum],
  "kuru_p1": [kuru_p1],
  "kuru_p2": [kuru_p2],
  "kuru_p3": [kuru_p3],
  "kuru_b1": [kuru_1_h],
  "kuru_b2": [kuru_2_h],
  "kuru_b3": [kuru_3_h],
  "kuru_b4": [kuru_4_h],
  "kuru_h1": [kuru_1_h],
  "kuru_h2": [kuru_2_h],
  "kuru_h3": [kuru_3_h],
  "kuru_h4": [kuru_4_h],
  "kuru_c1": [kuru_1_p],
  "kuru_c2": [kuru_2_p],
  "kuru_c3": [kuru_3_p],
  "kuru_c4": [kuru_4_p],
  "lily_h": [lily_h],
  "lily_p1": [lily_p1],
  "lily_p2": [lily_p2],
  "lily_p3": [lily_p3],
  "lily_b1": [lily_1_h],
  "lily_b2": [lily_2_h],
  "lily_b3": [lily_3_h],
  "lily_b4": [lily_4_h],
  "lily_h1": [lily_1_h],
  "lily_h2": [lily_2_h],
  "lily_h3": [lily_3_h],
  "lily_h4": [lily_4_h],
  "lily_c1": [lily_1_p],
  "lily_c2": [lily_2_p],
  "lily_c3": [lily_3_p],
  "lily_c4": [lily_4_p],
  "herb_h": [herb_h],
  "herb_p1": [herb_p1],
  "herb_p2": [herb_p2],
  "herb_p3": [herb_p3],
  "herb_b1": [herb_n1],
  "herb_b2": [herb_n2],
  "herb_h1": [herb_1_h],
  "herb_h2": [herb_2_h],
  "herb_c1": [herb_1_p],
  "herb_c2": [herb_2_p],
  "otherProduct_p": [otherProduct],
  "onlineShop_h": [onlineShop_h],
  "tharn_h": tharn_h,
  "tharn_p": tharn_p,
  "contactform_h": contact_h,
  "orderProduct_check": orderProduct,
  "orderOEM_check": orderOEM,
  "orderName": orderName,
  "orderOrg": orderOrg,
  "orderEmail": orderEmail,
  "orderTel": orderTel,
  "orderMsg": orderMsg,
  "drinkType": drinkType,
  "drinkType1_c": drinkType1,
  "drinkType2_c": drinkType2,
  "drinkType3_c": drinkType3,
  "drinkType4_c": drinkType4,
  "drinkType5_c": drinkType5,
  "packageType": packageType,
  "packageType1_c": packageType1,
  "packageType2_c": packageType2,
  "packageType3_c": packageType3,
  "packageType4_c": packageType4,
  "haveRecipe": haveRecipe,
  "haveRecipe1_c": haveRecipe1,
  "haveRecipe2_c": haveRecipe2,
  "howyouknowus": howyouknowus
};

// Loop through the ID map and set the content dynamically
for (const id in idMap) {
  const element = document.getElementById(id);
  if (element) {
    element.innerHTML = idMap[id][lang];
  }
}